/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Effekseer.swig;

@SuppressWarnings({"unused", "RedundantSuppression"})
public final class EffekseerCoreDeviceType {
  public final static EffekseerCoreDeviceType Unknown = new EffekseerCoreDeviceType("Unknown");
  public final static EffekseerCoreDeviceType OpenGL = new EffekseerCoreDeviceType("OpenGL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EffekseerCoreDeviceType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    // was originally a normal fori loop
    for (EffekseerCoreDeviceType value : swigValues)
      if (value.swigValue == swigValue)
        return value;
    throw new IllegalArgumentException("No enum " + EffekseerCoreDeviceType.class + " with value " + swigValue);
  }

  private EffekseerCoreDeviceType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EffekseerCoreDeviceType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EffekseerCoreDeviceType(String swigName, EffekseerCoreDeviceType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static final EffekseerCoreDeviceType[] swigValues = { Unknown, OpenGL }; // was originally non-final
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

